services:
  scraper:
    image: ghcr.io/jeevonix/postleads-scraper:latest
    container_name: scraper-api
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - cft-network
      - default

networks:
  cft-network:
    external: true
  default:
    name: bridge